//
//  LocalizedUI.kt
//  AccessEye
//
//  The app's spoken + on-screen wording follows the user's CHOSEN output
//  language (not the device locale), because that's the language the blind user
//  asked to hear. Descriptions themselves come from Gemma in that language; this
//  table covers the app's own status/labels so the whole experience is
//  consistent. (README §6.4, §7.)
//
//  Android port of Support/LocalizedUI.swift. The onboarding / model-management
//  strings that were English-only on iOS are fully localized here.
//

package gr.orestislef.accesseye.support

import gr.orestislef.accesseye.model.Language

data class UiText(
    val gettingReady: String, val ready: String, val describing: String,
    val tapToDescribe: String, val repeatLast: String, val history: String,
    val settings: String, val language: String, val speechSpeed: String,
    val noHistory: String, val clearHistory: String, val cameraNeeded: String,
    val notReady: String, val done: String,
    val stop: String, val clear: String, val tapToHear: String,
    // Android-only additions (onboarding, model management, accessibility hints):
    val welcomeTitle: String,
    val welcomeBody: String,           // contains %s for model size text
    val downloadModel: String,
    val downloadModelHint: String,     // a11y: downloads the model so the app can work offline
    val cancel: String, val tryAgain: String, val openSettings: String,
    val aiModel: String, val status: String, val downloaded: String,
    val notInstalled: String, val downloading: String, // progress % appended
    val sizeOnDevice: String, val deleteModel: String,
    val deleteModelConfirmTitle: String,
    val deleteModelConfirmBody: String,    // contains %s for size
    val deleteModelHint: String,       // a11y: frees space, need to re-download
    val describeHint: String,          // a11y: captures what the camera sees and describes it aloud
    val playsAgainHint: String,        // a11y on history rows
    val delete: String,
    val voiceMissing: String,
    val installVoice: String,
    val speedLabel: String, val etaLabel: String,
    val percentLoaded: String,         // "%d percent" for a11y announcements
    val appStarting: String,
)

object LocalizedUI {
    fun textFor(language: Language): UiText = when (language) {
        Language.ENGLISH -> UiText(
            gettingReady = "Getting things ready…",
            ready = "Ready. Tap anywhere to describe what's in front of you.",
            describing = "Looking…",
            tapToDescribe = "Tap to describe",
            repeatLast = "Repeat",
            history = "History",
            settings = "Settings",
            language = "Language",
            speechSpeed = "Speech speed",
            noHistory = "No descriptions yet.",
            clearHistory = "Clear history",
            cameraNeeded = "Camera access is needed. Please turn it on in Settings.",
            notReady = "Couldn't get the AI ready.",
            done = "Done",
            stop = "Stop",
            clear = "Clear",
            tapToHear = "Tap to hear again",
            welcomeTitle = "Welcome to AccessEye",
            welcomeBody = "AccessEye describes the world around you out loud — completely on your device, with no internet needed once set up.\n\nTo work offline, it needs to download its AI model one time (%s). Please stay on Wi-Fi.",
            downloadModel = "Download the AI model",
            downloadModelHint = "Downloads the AI model so the app can work offline",
            cancel = "Cancel",
            tryAgain = "Try again",
            openSettings = "Open Settings",
            aiModel = "AI Model",
            status = "Status",
            downloaded = "Downloaded",
            notInstalled = "Not installed",
            downloading = "Downloading",
            sizeOnDevice = "Size on device",
            deleteModel = "Delete model",
            deleteModelConfirmTitle = "Delete the AI model?",
            deleteModelConfirmBody = "This removes the %s model from your device. You can download it again any time.",
            deleteModelHint = "Frees up space. You'll need to download the model again to use the app.",
            describeHint = "Captures what the camera sees and describes it aloud",
            playsAgainHint = "Plays this description again",
            delete = "Delete",
            voiceMissing = "The voice for this language is not installed. Install it in text-to-speech settings.",
            installVoice = "Install voice",
            speedLabel = "Speed",
            etaLabel = "Time left",
            percentLoaded = "%d percent",
            appStarting = "AccessEye is starting")

        Language.GREEK -> UiText(
            gettingReady = "Ετοιμάζομαι…",
            ready = "Έτοιμο. Αγγίξτε οπουδήποτε για να περιγράψω τι είναι μπροστά σας.",
            describing = "Κοιτάζω…",
            tapToDescribe = "Αγγίξτε για περιγραφή",
            repeatLast = "Επανάληψη",
            history = "Ιστορικό",
            settings = "Ρυθμίσεις",
            language = "Γλώσσα",
            speechSpeed = "Ταχύτητα ομιλίας",
            noHistory = "Δεν υπάρχουν περιγραφές ακόμη.",
            clearHistory = "Εκκαθάριση ιστορικού",
            cameraNeeded = "Απαιτείται πρόσβαση στην κάμερα. Ενεργοποιήστε την στις Ρυθμίσεις.",
            notReady = "Δεν ήταν δυνατή η προετοιμασία της τεχνητής νοημοσύνης.",
            done = "Τέλος",
            stop = "Διακοπή",
            clear = "Καθαρισμός",
            tapToHear = "Αγγίξτε για ακρόαση ξανά",
            welcomeTitle = "Καλώς ήρθατε στο AccessEye",
            welcomeBody = "Το AccessEye περιγράφει φωναχτά τον κόσμο γύρω σας — εξ ολοκλήρου στη συσκευή σας, χωρίς να χρειάζεται ίντερνετ μετά την αρχική ρύθμιση.\n\nΓια να λειτουργεί εκτός σύνδεσης, χρειάζεται να κατεβάσει μία φορά το μοντέλο τεχνητής νοημοσύνης (%s). Παρακαλούμε μείνετε συνδεδεμένοι σε Wi-Fi.",
            downloadModel = "Λήψη του μοντέλου τεχνητής νοημοσύνης",
            downloadModelHint = "Κατεβάζει το μοντέλο τεχνητής νοημοσύνης ώστε η εφαρμογή να λειτουργεί χωρίς σύνδεση",
            cancel = "Άκυρο",
            tryAgain = "Δοκιμάστε ξανά",
            openSettings = "Άνοιγμα Ρυθμίσεων",
            aiModel = "Μοντέλο τεχνητής νοημοσύνης",
            status = "Κατάσταση",
            downloaded = "Έχει ληφθεί",
            notInstalled = "Δεν έχει εγκατασταθεί",
            downloading = "Λήψη",
            sizeOnDevice = "Μέγεθος στη συσκευή",
            deleteModel = "Διαγραφή μοντέλου",
            deleteModelConfirmTitle = "Διαγραφή του μοντέλου τεχνητής νοημοσύνης;",
            deleteModelConfirmBody = "Αυτό αφαιρεί το μοντέλο των %s από τη συσκευή σας. Μπορείτε να το κατεβάσετε ξανά όποτε θέλετε.",
            deleteModelHint = "Ελευθερώνει χώρο. Θα χρειαστεί να κατεβάσετε ξανά το μοντέλο για να χρησιμοποιήσετε την εφαρμογή.",
            describeHint = "Καταγράφει ό,τι βλέπει η κάμερα και το περιγράφει φωναχτά",
            playsAgainHint = "Αναπαράγει ξανά αυτή την περιγραφή",
            delete = "Διαγραφή",
            voiceMissing = "Η φωνή για αυτή τη γλώσσα δεν είναι εγκατεστημένη. Εγκαταστήστε την στις ρυθμίσεις μετατροπής κειμένου σε ομιλία.",
            installVoice = "Εγκατάσταση φωνής",
            speedLabel = "Ταχύτητα",
            etaLabel = "Χρόνος που απομένει",
            percentLoaded = "%d τοις εκατό",
            appStarting = "Το AccessEye ξεκινά")

        Language.SPANISH -> UiText(
            gettingReady = "Preparando todo…",
            ready = "Listo. Toca en cualquier lugar para describir lo que tienes delante.",
            describing = "Mirando…",
            tapToDescribe = "Toca para describir",
            repeatLast = "Repetir",
            history = "Historial",
            settings = "Ajustes",
            language = "Idioma",
            speechSpeed = "Velocidad de voz",
            noHistory = "Aún no hay descripciones.",
            clearHistory = "Borrar historial",
            cameraNeeded = "Se necesita acceso a la cámara. Actívalo en Ajustes.",
            notReady = "No se pudo preparar la IA.",
            done = "Hecho",
            stop = "Detener",
            clear = "Borrar",
            tapToHear = "Toca para escuchar de nuevo",
            welcomeTitle = "Te damos la bienvenida a AccessEye",
            welcomeBody = "AccessEye describe en voz alta el mundo que te rodea — completamente en tu dispositivo, sin necesidad de internet una vez configurado.\n\nPara funcionar sin conexión, necesita descargar su modelo de IA una sola vez (%s). Mantente conectado a una red Wi-Fi.",
            downloadModel = "Descargar el modelo de IA",
            downloadModelHint = "Descarga el modelo de IA para que la app funcione sin conexión",
            cancel = "Cancelar",
            tryAgain = "Inténtalo de nuevo",
            openSettings = "Abrir Ajustes",
            aiModel = "Modelo de IA",
            status = "Estado",
            downloaded = "Descargado",
            notInstalled = "No instalado",
            downloading = "Descargando",
            sizeOnDevice = "Tamaño en el dispositivo",
            deleteModel = "Eliminar modelo",
            deleteModelConfirmTitle = "¿Eliminar el modelo de IA?",
            deleteModelConfirmBody = "Esto elimina el modelo de %s de tu dispositivo. Puedes descargarlo de nuevo cuando quieras.",
            deleteModelHint = "Libera espacio. Tendrás que descargar el modelo de nuevo para usar la app.",
            describeHint = "Captura lo que ve la cámara y lo describe en voz alta",
            playsAgainHint = "Reproduce esta descripción de nuevo",
            delete = "Eliminar",
            voiceMissing = "La voz para este idioma no está instalada. Instálala en los ajustes de texto a voz.",
            installVoice = "Instalar voz",
            speedLabel = "Velocidad",
            etaLabel = "Tiempo restante",
            percentLoaded = "%d por ciento",
            appStarting = "AccessEye se está iniciando")

        Language.FRENCH -> UiText(
            gettingReady = "Préparation en cours…",
            ready = "Prêt. Touchez n'importe où pour décrire ce qui est devant vous.",
            describing = "Observation…",
            tapToDescribe = "Touchez pour décrire",
            repeatLast = "Répéter",
            history = "Historique",
            settings = "Réglages",
            language = "Langue",
            speechSpeed = "Vitesse de parole",
            noHistory = "Aucune description pour l'instant.",
            clearHistory = "Effacer l'historique",
            cameraNeeded = "L'accès à la caméra est nécessaire. Activez-le dans Réglages.",
            notReady = "Impossible de préparer l'IA.",
            done = "Terminé",
            stop = "Arrêter",
            clear = "Effacer",
            tapToHear = "Touchez pour réécouter",
            welcomeTitle = "Bienvenue dans AccessEye",
            welcomeBody = "AccessEye décrit à voix haute le monde qui vous entoure — entièrement sur votre appareil, sans internet une fois la configuration terminée.\n\nPour fonctionner hors ligne, l'application doit télécharger son modèle d'IA une seule fois (%s). Veuillez rester en Wi-Fi.",
            downloadModel = "Télécharger le modèle d'IA",
            downloadModelHint = "Télécharge le modèle d'IA pour que l'application fonctionne hors ligne",
            cancel = "Annuler",
            tryAgain = "Réessayer",
            openSettings = "Ouvrir les Réglages",
            aiModel = "Modèle d'IA",
            status = "État",
            downloaded = "Téléchargé",
            notInstalled = "Non installé",
            downloading = "Téléchargement",
            sizeOnDevice = "Taille sur l'appareil",
            deleteModel = "Supprimer le modèle",
            deleteModelConfirmTitle = "Supprimer le modèle d'IA ?",
            deleteModelConfirmBody = "Cela supprime le modèle de %s de votre appareil. Vous pourrez le retélécharger à tout moment.",
            deleteModelHint = "Libère de l'espace. Vous devrez retélécharger le modèle pour utiliser l'application.",
            describeHint = "Capture ce que voit la caméra et le décrit à voix haute",
            playsAgainHint = "Rejoue cette description",
            delete = "Supprimer",
            voiceMissing = "La voix pour cette langue n'est pas installée. Installez-la dans les réglages de synthèse vocale.",
            installVoice = "Installer la voix",
            speedLabel = "Vitesse",
            etaLabel = "Temps restant",
            percentLoaded = "%d pour cent",
            appStarting = "AccessEye démarre")

        Language.GERMAN -> UiText(
            gettingReady = "Wird vorbereitet…",
            ready = "Bereit. Tippen Sie irgendwo, um zu beschreiben, was vor Ihnen ist.",
            describing = "Schaue…",
            tapToDescribe = "Zum Beschreiben tippen",
            repeatLast = "Wiederholen",
            history = "Verlauf",
            settings = "Einstellungen",
            language = "Sprache",
            speechSpeed = "Sprechgeschwindigkeit",
            noHistory = "Noch keine Beschreibungen.",
            clearHistory = "Verlauf löschen",
            cameraNeeded = "Kamerazugriff ist erforderlich. Bitte in den Einstellungen aktivieren.",
            notReady = "Die KI konnte nicht vorbereitet werden.",
            done = "Fertig",
            stop = "Stopp",
            clear = "Löschen",
            tapToHear = "Zum erneuten Anhören tippen",
            welcomeTitle = "Willkommen bei AccessEye",
            welcomeBody = "AccessEye beschreibt Ihnen die Welt um Sie herum laut — vollständig auf Ihrem Gerät, nach der Einrichtung ganz ohne Internet.\n\nUm offline zu funktionieren, muss die App einmalig ihr KI-Modell herunterladen (%s). Bitte bleiben Sie im WLAN.",
            downloadModel = "KI-Modell herunterladen",
            downloadModelHint = "Lädt das KI-Modell herunter, damit die App offline funktioniert",
            cancel = "Abbrechen",
            tryAgain = "Erneut versuchen",
            openSettings = "Einstellungen öffnen",
            aiModel = "KI-Modell",
            status = "Status",
            downloaded = "Heruntergeladen",
            notInstalled = "Nicht installiert",
            downloading = "Wird heruntergeladen",
            sizeOnDevice = "Größe auf dem Gerät",
            deleteModel = "Modell löschen",
            deleteModelConfirmTitle = "KI-Modell löschen?",
            deleteModelConfirmBody = "Dadurch wird das %s große Modell von Ihrem Gerät entfernt. Sie können es jederzeit erneut herunterladen.",
            deleteModelHint = "Gibt Speicherplatz frei. Sie müssen das Modell erneut herunterladen, um die App zu verwenden.",
            describeHint = "Erfasst, was die Kamera sieht, und beschreibt es laut",
            playsAgainHint = "Spielt diese Beschreibung erneut ab",
            delete = "Löschen",
            voiceMissing = "Die Stimme für diese Sprache ist nicht installiert. Installieren Sie sie in den Text-zu-Sprache-Einstellungen.",
            installVoice = "Stimme installieren",
            speedLabel = "Geschwindigkeit",
            etaLabel = "Verbleibende Zeit",
            percentLoaded = "%d Prozent",
            appStarting = "AccessEye startet")

        Language.ARABIC -> UiText(
            gettingReady = "جارٍ التحضير…",
            ready = "جاهز. المس أي مكان لوصف ما أمامك.",
            describing = "جارٍ النظر…",
            tapToDescribe = "المس للوصف",
            repeatLast = "إعادة",
            history = "السجل",
            settings = "الإعدادات",
            language = "اللغة",
            speechSpeed = "سرعة الكلام",
            noHistory = "لا توجد أوصاف بعد.",
            clearHistory = "مسح السجل",
            cameraNeeded = "يلزم الوصول إلى الكاميرا. يرجى تفعيله من الإعدادات.",
            notReady = "تعذّر تجهيز الذكاء الاصطناعي.",
            done = "تم",
            stop = "إيقاف",
            clear = "مسح",
            tapToHear = "المس للاستماع مرة أخرى",
            welcomeTitle = "مرحبًا بك في AccessEye",
            welcomeBody = "يصف AccessEye العالم من حولك بصوت مسموع — بالكامل على جهازك، دون الحاجة إلى الإنترنت بعد الإعداد.\n\nللعمل دون اتصال، يحتاج التطبيق إلى تنزيل نموذج الذكاء الاصطناعي مرة واحدة (%s). يرجى البقاء متصلاً بشبكة Wi-Fi.",
            downloadModel = "تنزيل نموذج الذكاء الاصطناعي",
            downloadModelHint = "ينزّل نموذج الذكاء الاصطناعي ليعمل التطبيق دون اتصال بالإنترنت",
            cancel = "إلغاء",
            tryAgain = "حاول مرة أخرى",
            openSettings = "فتح الإعدادات",
            aiModel = "نموذج الذكاء الاصطناعي",
            status = "الحالة",
            downloaded = "تم التنزيل",
            notInstalled = "غير مثبّت",
            downloading = "جارٍ التنزيل",
            sizeOnDevice = "الحجم على الجهاز",
            deleteModel = "حذف النموذج",
            deleteModelConfirmTitle = "هل تريد حذف نموذج الذكاء الاصطناعي؟",
            deleteModelConfirmBody = "سيؤدي هذا إلى إزالة النموذج البالغ حجمه %s من جهازك. يمكنك تنزيله مرة أخرى في أي وقت.",
            deleteModelHint = "يوفّر مساحة تخزين. ستحتاج إلى تنزيل النموذج مرة أخرى لاستخدام التطبيق.",
            describeHint = "يلتقط ما تراه الكاميرا ويصفه بصوت مسموع",
            playsAgainHint = "يعيد تشغيل هذا الوصف",
            delete = "حذف",
            voiceMissing = "صوت هذه اللغة غير مثبّت. ثبّته من إعدادات تحويل النص إلى كلام.",
            installVoice = "تثبيت الصوت",
            speedLabel = "السرعة",
            etaLabel = "الوقت المتبقي",
            percentLoaded = "%d بالمئة",
            appStarting = "جارٍ تشغيل AccessEye")

        Language.HINDI -> UiText(
            gettingReady = "तैयारी हो रही है…",
            ready = "तैयार। आपके सामने जो है उसका वर्णन करने के लिए कहीं भी टैप करें।",
            describing = "देख रहा हूँ…",
            tapToDescribe = "वर्णन के लिए टैप करें",
            repeatLast = "दोहराएँ",
            history = "इतिहास",
            settings = "सेटिंग्ज़",
            language = "भाषा",
            speechSpeed = "बोलने की गति",
            noHistory = "अभी तक कोई वर्णन नहीं।",
            clearHistory = "इतिहास साफ़ करें",
            cameraNeeded = "कैमरा एक्सेस आवश्यक है। कृपया इसे सेटिंग्ज़ में चालू करें।",
            notReady = "एआई तैयार नहीं हो सका।",
            done = "हो गया",
            stop = "रोकें",
            clear = "हटाएँ",
            tapToHear = "फिर से सुनने के लिए टैप करें",
            welcomeTitle = "AccessEye में आपका स्वागत है",
            welcomeBody = "AccessEye आपके आस-पास की दुनिया का वर्णन बोलकर करता है — पूरी तरह आपके डिवाइस पर, और एक बार सेट हो जाने के बाद इंटरनेट की ज़रूरत नहीं।\n\nऑफ़लाइन काम करने के लिए इसे अपना एआई मॉडल एक बार डाउनलोड करना होगा (%s)। कृपया वाई-फ़ाई से जुड़े रहें।",
            downloadModel = "एआई मॉडल डाउनलोड करें",
            downloadModelHint = "एआई मॉडल डाउनलोड करता है ताकि ऐप ऑफ़लाइन काम कर सके",
            cancel = "रद्द करें",
            tryAgain = "फिर से कोशिश करें",
            openSettings = "सेटिंग्ज़ खोलें",
            aiModel = "एआई मॉडल",
            status = "स्थिति",
            downloaded = "डाउनलोड हो गया",
            notInstalled = "इंस्टॉल नहीं है",
            downloading = "डाउनलोड हो रहा है",
            sizeOnDevice = "डिवाइस पर आकार",
            deleteModel = "मॉडल हटाएँ",
            deleteModelConfirmTitle = "एआई मॉडल हटाएँ?",
            deleteModelConfirmBody = "इससे %s का मॉडल आपके डिवाइस से हट जाएगा। आप इसे कभी भी दोबारा डाउनलोड कर सकते हैं।",
            deleteModelHint = "जगह खाली करता है। ऐप इस्तेमाल करने के लिए आपको मॉडल दोबारा डाउनलोड करना होगा।",
            describeHint = "कैमरे को जो दिखता है उसे कैप्चर करके बोलकर बताता है",
            playsAgainHint = "यह वर्णन दोबारा सुनाता है",
            delete = "हटाएँ",
            voiceMissing = "इस भाषा की आवाज़ इंस्टॉल नहीं है। इसे टेक्स्ट-टू-स्पीच सेटिंग्ज़ में इंस्टॉल करें।",
            installVoice = "आवाज़ इंस्टॉल करें",
            speedLabel = "गति",
            etaLabel = "बचा हुआ समय",
            percentLoaded = "%d प्रतिशत",
            appStarting = "AccessEye शुरू हो रहा है")

        Language.ITALIAN -> UiText(
            gettingReady = "Preparazione in corso…",
            ready = "Pronto. Tocca ovunque per descrivere ciò che hai davanti.",
            describing = "Sto guardando…",
            tapToDescribe = "Tocca per descrivere",
            repeatLast = "Ripeti",
            history = "Cronologia",
            settings = "Impostazioni",
            language = "Lingua",
            speechSpeed = "Velocità del parlato",
            noHistory = "Ancora nessuna descrizione.",
            clearHistory = "Cancella cronologia",
            cameraNeeded = "È necessario l'accesso alla fotocamera. Attivalo in Impostazioni.",
            notReady = "Impossibile preparare l'IA.",
            done = "Fatto",
            stop = "Ferma",
            clear = "Cancella",
            tapToHear = "Tocca per riascoltare",
            welcomeTitle = "Ti diamo il benvenuto in AccessEye",
            welcomeBody = "AccessEye descrive ad alta voce il mondo intorno a te — interamente sul tuo dispositivo, senza bisogno di internet una volta configurato.\n\nPer funzionare offline, deve scaricare il suo modello di IA una sola volta (%s). Resta connesso al Wi-Fi.",
            downloadModel = "Scarica il modello di IA",
            downloadModelHint = "Scarica il modello di IA così l'app può funzionare offline",
            cancel = "Annulla",
            tryAgain = "Riprova",
            openSettings = "Apri Impostazioni",
            aiModel = "Modello di IA",
            status = "Stato",
            downloaded = "Scaricato",
            notInstalled = "Non installato",
            downloading = "Download in corso",
            sizeOnDevice = "Dimensioni sul dispositivo",
            deleteModel = "Elimina modello",
            deleteModelConfirmTitle = "Eliminare il modello di IA?",
            deleteModelConfirmBody = "Questo rimuove il modello da %s dal tuo dispositivo. Puoi scaricarlo di nuovo in qualsiasi momento.",
            deleteModelHint = "Libera spazio. Dovrai scaricare di nuovo il modello per usare l'app.",
            describeHint = "Cattura ciò che vede la fotocamera e lo descrive ad alta voce",
            playsAgainHint = "Riproduce di nuovo questa descrizione",
            delete = "Elimina",
            voiceMissing = "La voce per questa lingua non è installata. Installala nelle impostazioni di sintesi vocale.",
            installVoice = "Installa voce",
            speedLabel = "Velocità",
            etaLabel = "Tempo rimanente",
            percentLoaded = "%d per cento",
            appStarting = "AccessEye si sta avviando")

        Language.RUSSIAN -> UiText(
            gettingReady = "Подготовка…",
            ready = "Готово. Коснитесь в любом месте, чтобы описать, что перед вами.",
            describing = "Смотрю…",
            tapToDescribe = "Коснитесь, чтобы описать",
            repeatLast = "Повторить",
            history = "История",
            settings = "Настройки",
            language = "Язык",
            speechSpeed = "Скорость речи",
            noHistory = "Пока нет описаний.",
            clearHistory = "Очистить историю",
            cameraNeeded = "Требуется доступ к камере. Включите его в Настройках.",
            notReady = "Не удалось подготовить ИИ.",
            done = "Готово",
            stop = "Стоп",
            clear = "Очистить",
            tapToHear = "Коснитесь, чтобы прослушать снова",
            welcomeTitle = "Добро пожаловать в AccessEye",
            welcomeBody = "AccessEye вслух описывает мир вокруг вас — полностью на вашем устройстве, без интернета после первоначальной настройки.\n\nЧтобы работать офлайн, приложению нужно один раз скачать модель искусственного интеллекта (%s). Пожалуйста, оставайтесь в сети Wi-Fi.",
            downloadModel = "Скачать модель ИИ",
            downloadModelHint = "Скачивает модель ИИ, чтобы приложение работало без интернета",
            cancel = "Отмена",
            tryAgain = "Повторить попытку",
            openSettings = "Открыть настройки",
            aiModel = "Модель ИИ",
            status = "Статус",
            downloaded = "Скачана",
            notInstalled = "Не установлена",
            downloading = "Скачивание",
            sizeOnDevice = "Размер на устройстве",
            deleteModel = "Удалить модель",
            deleteModelConfirmTitle = "Удалить модель ИИ?",
            deleteModelConfirmBody = "Модель размером %s будет удалена с вашего устройства. Вы можете скачать её снова в любое время.",
            deleteModelHint = "Освобождает место. Чтобы пользоваться приложением, модель придётся скачать заново.",
            describeHint = "Снимает то, что видит камера, и описывает это вслух",
            playsAgainHint = "Воспроизводит это описание ещё раз",
            delete = "Удалить",
            voiceMissing = "Голос для этого языка не установлен. Установите его в настройках синтеза речи.",
            installVoice = "Установить голос",
            speedLabel = "Скорость",
            etaLabel = "Оставшееся время",
            percentLoaded = "%d процентов",
            appStarting = "AccessEye запускается")
    }
}
